# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaaacb66825c6fef6a74fea3abed8968611be3390f1845d7ef44dd026e349567a4a0c0e007d6cae5997ab20e676093d95183d635b25e0cfde13f01917d297e85

test:
  secret_key_base: 7239a7d2da6c0dd030ead7e5dd2fb09e2c6025aab1d95356ba29c32de7fbf7b267927b345adde7a700fb854515b796c694827b1f810f6b19d3d261bd70ec3902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
