# Scaffolding generated by Caseadilla 1.0.0

module Caseadilla
  class PostsController < Caseadilla::CaseadillaController

    ## optional filters for defining usage according to Caseadilla::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]

    def index
      @caseadilla_page_title = 'Post'
  		@posts = Post.order(sort_order(:title)).paginate :page => params[:page]
    end

    def show
      @caseadilla_page_title = 'View posts'
      @posts = Post.find params[:id]
    end

    def new
      @caseadilla_page_title = 'Add a new posts'
    	@posts = Post.new
    end

    def create
      @posts = Post.new posts_params

      if @posts.save
        flash[:notice] = 'Post created'
        redirect_to caseadilla_posts_index_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new posts'
        render :action => :new
      end
    end

    def update
      @caseadilla_page_title = 'Update posts'

      @posts = Post.find params[:id]

      if @posts.update_attributes posts_params
        flash[:notice] = 'Post has been updated'
        redirect_to caseadilla_posts_index_path
      else
        flash.now[:warning] = 'There were problems when trying to update this posts'
        render :action => :show
      end
    end

    def destroy
      @posts = Post.find params[:id]

      @posts.destroy
      flash[:notice] = 'Post has been deleted'
      redirect_to caseadilla_posts_index_path
    end

    private

      def posts_params
        params.require(:posts).permit(:title, :body, :user_id)
      end

  end
end
